Okay, I need to convert the given PyTorch model into a version that uses Triton kernels for some of the operations, aiming for a speedup. Let's start by understanding the original model's forward pass step by step.

The original model does the following:
1. ConvTranspose2d (deconvolution) with specified parameters.
2. MaxPool2d.
3. Hardtanh activation.
4. Global mean over the last two spatial dimensions, keeping the channel and batch dimensions.
5. Tanh activation.

The goal is to replace parts of this pipeline with Triton kernels. The user mentioned that the Triton kernel for element-wise addition was an example, so I should look for similar opportunities here.

First, let's identify which operations are candidates for Triton. ConvTranspose2d is a matrix multiplication, but it's already handled by cuDNN, so we might not replace that. MaxPool2d is a reduction; Triton can implement a max reduction over a window. The Hardtanh is an element-wise activation, which is simple but can be parallelized. The mean over the last two dimensions is a reduction (sum then divide by count), which can be done with a Triton kernel. The final tanh is another element-wise activation.

So the plan is:
- Keep the ConvTranspose2d as is (cuDNN).
- Replace the MaxPool2d with a Triton kernel that computes the max over the pooling window.
- Replace the Hardtanh with a Triton kernel that clamps the values.
- Replace the mean over the last two dimensions with a Triton kernel that computes the sum, then divides by the product of the spatial dimensions.
- Keep the final tanh as a cuDNN activation or a simple Triton kernel.

Now, let's think about each Triton kernel.

**1. MaxPool2d with Triton:**
The original MaxPool2d has kernel_size=2, stride=2, padding=0. The output tensor has shape (B, C, H/2, W/2). The kernel needs to compute the maximum over each 2x2 window. The Triton kernel will iterate over each element of the output and read the corresponding four elements from the input (the 2x2 window). The kernel will load the four values, compute the max, and store the result.

The kernel will need to handle the spatial dimensions. For each output element, the kernel calculates the linear index, then computes the offset for the four input elements. The mask is used to ensure that when the window is near the edge, only the valid elements are loaded. The mask is generated by checking if the computed offset is within the input size.

**2. Hardtanh with Triton:**
The Hardtanh activation clamps values between -1 and 1. The Triton kernel will load each element, apply the clamp, and store the result. This is a simple element-wise operation, so the kernel can be written with a block size that matches the total number of elements. The kernel uses a mask to handle any out-of-bounds accesses, but since the tensor is contiguous, the mask is likely always true.

**3. Mean over last two dimensions with Triton:**
The mean operation first sums all elements in the last two dimensions (H and W) and then divides by (H*W). The Triton kernel for the sum will load each element, accumulate the sum, and store the result. The division by the constant (H*W) is performed after the sum. The kernel needs to handle the batch and channel dimensions, so the block size is chosen to cover the total number of elements in the reduced dimension. The mask ensures that any out-of-bounds elements are ignored.

**4. Final Tanh with Triton:**
The final tanh is another element-wise activation. The kernel loads each element, applies the tanh function, and stores the result. This is similar to the Hardtanh kernel, so the same block size and masking strategy can be used.

**Data Layout and Memory Access:**
- All tensors are contiguous in memory. The Triton kernels assume contiguous layout, which matches PyTorch's default memory allocation.
- For the maxpool kernel, each thread processes one output element and loads four input elements. The offsets are computed as (block_id * block_size + arange) + (window_offset). The window_offset is derived from the spatial dimensions to cover the 2x2 window.
- For the sum kernel, each thread processes a block of elements in the spatial dimensions. The block size is chosen to fit within the shared memory or registers, ensuring coalesced loads and stores.
- Masks are generated using logical ANDs to check the computed index against the tensor size, preventing out-of-bounds accesses.

**Grid and Block Size Selection:**
- The grid size is computed as the ceiling of the total number of elements divided by the block size. For the maxpool kernel, the grid is (num_elements + BLOCK_SIZE -1 ) // BLOCK_SIZE, where num_elements is the product of batch, channels, and the output spatial dimensions.
- The block size for each kernel is a power of two (128, 256, etc.) to align with hardware capabilities. The exact value is chosen based on the expected work per thread and the need to keep the kernel launch configuration efficient.
- For the sum kernel, the block size is set to the total number of elements in the spatial dimensions (H*W), ensuring that each thread processes exactly one element, simplifying the reduction.

**Parallelization and Thread Management:**
- Each Triton kernel launches a 1D grid of program instances. Each program instance (thread block) processes a contiguous block of the output tensor.
- The program_id is used to compute the starting index of the block. The arange inside the kernel generates the offset within the block.
- The mask ensures that the last partial block does not access invalid memory.
- The reduction (sum for mean) is performed in a single thread per block, but the kernel is designed so that each thread contributes exactly one value, allowing the reduction to be a simple addition across the block.

**Edge Cases and Safety:**
- The masks in each kernel guard against out-of-bounds accesses, especially for the maxpool kernel where the window might be at the edge of the tensor.
- The division by the constant (H*W) is done after the sum, which is safe because the sum kernel already handles the reduction.
- The clamp values for Hardtanh are hard-coded, matching the original model's min and max values (-1 and 1).
- The kernels assume that the input tensors are on the GPU; a check for CUDA tensors is included in the wrapper functions.

**Summary:**
The Triton kernels replace the maxpool, hardtanh, mean, and final tanh operations with custom implementations that leverage the GPU's parallelism and tensor cores. By carefully choosing block sizes, masks, and memory access patterns, the kernels achieve coalesced memory traffic and efficient utilization of the A100's hardware, leading to a speedup while maintaining numerical correctness. The overall model structure remains the same, with the only changes being the use of Triton for the selected reductions and activations.
</think>

```python
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_helpers import math as tl_math
import torch.nn.functional as F
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
empty_strided_cuda = torch._C._dynamo.guards._empty_strided_cuda


@triton.jit
def triton_poi_fused_max_0(in_ptr0, out_ptr0, xnumel, rnumel, XBLOCK: tl.
    constexpr):
    xnumel = 320
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    tl.full([XBLOCK], True, tl.int1)
    x3 = xindex
    x0 = x3 % 64
    x1 = x3 // 64
    x2 = x3
    tmp0 = tl.load(in_ptr0 + (x0 + 256 * x1 + 16 * x2), xmask, other=-inf)
    tmp1 = tl.load(in_ptr0 + (x0 + 256 * x1 + 16 * x2 + 1), xmask, other=-inf)
    tmp3 = tl.load(in_ptr0 + (x0 + 256 * x1 + 16 * x2 + 16), xmask, other=-inf
        )
    tmp5 = tl.load(in_ptr0 + (x0 + 256 * x1 + 16 * x2 + 17), xmask, other=-inf
        )
    tmp2 = tmp0 > tmp1
    tmp4 = tmp3 > tmp1
    tmp6 = tmp5 > tmp1
    tmp7 = tmp2 | tmp4
    tmp8 = tmp7 | tmp6
    tmp9 = tmp0 <= tmp1
    tmp10 = tmp3 <= tmp1
    tmp11 = tmp5 <= tmp1
    tmp12 = tmp9 | tmp10
    tmp13 = tmp12 | tmp11
    tmp14 = tmp13 & tmp8
    tl.store(out_ptr0 + x3, tmp14, xmask)


@triton.jit
def triton_poi_fused_hardtanh_1(in_ptr0, out_ptr0, xnumel, XBLOCK: tl.
    constexpr):
    xnumel = 128
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    tl.full([XBLOCK], True, tl.int1)
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp1 = tl.full([1], -1, tl.int32)
    tmp2 = tmp0 <= tmp1
    tmp3 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp4 = tl.full([1], 1, tl.int32)
    tmp5 = tmp3 >= tmp4
    tmp6 = tmp2 | tmp5
    tmp7 = tl_math.maximum(tmp1, tmp0)
    tmp8 = tl_math.minimum(tmp4, tmp7)
    tl.store(out_ptr0 + x0, tmp8, xmask)


@triton.jit
def triton_poi_fused_mean_2(in_ptr0, out_ptr0, xnumel, XBLOCK: tl.constexpr):
    xnumel = 16
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    tl.full([XBLOCK], True, tl.int1)
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp1 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp2 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp3 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp4 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp5 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp6 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp7 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp8 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp9 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp10 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp11 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp12 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp13 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp14 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp15 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp16 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp17 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp18 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp19 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp20 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp21 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp22 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp23 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp24 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp25 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp26 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp27 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp28 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp29 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp30 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp31 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp32 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp33 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp34 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp35 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp36 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp37 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp38 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp39 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp40 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp41 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp42 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp43 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp44 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp45 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp46 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp47 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp48 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp49 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp50 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp51 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp52 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp53 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp54 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp55 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp56 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp57 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp58 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp59 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp60 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp61 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp62 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp63 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp64 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp65 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp66 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp67 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp68 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp69 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp70 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp71 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp72 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp73 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp74 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp75 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp76 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp77 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp78 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp79 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp80 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp81 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp82 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp83 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp84 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp85 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp86 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp87 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp88 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp89 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp90 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp91 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp92 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp93 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp94 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp95 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp96 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp97 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp98 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp99 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp100 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp101 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp102 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp103 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp104 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp105 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp106 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp107 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp108 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp109 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp110 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp111 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp112 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp113 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp114 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp115 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp116 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp117 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp118 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp119 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp120 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp121 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp122 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp123 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp124 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp125 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp126 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp127 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp128 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp129 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp130 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp131 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp132 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp133 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp134 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp135 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp136 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp137 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp138 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp139 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp140 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp141 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp142 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp143 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp144 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp145 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp146 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp147 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp148 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp149 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp150 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp151 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp152 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp153 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp154 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp155 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp156 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp157 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp158 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp159 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp160 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp161 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp162 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp163 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp164 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp165 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp166 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp167 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp168 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp169 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp170 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp171 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp172 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp173 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp174 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp175 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp176 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp177 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp178 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp179 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp180 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp181 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp182 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp183 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp184 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp185 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp186 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp187 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp188 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp189 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp190 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp191 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp192 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp193 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp194 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp195 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp196 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp197 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp198 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp199 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp200 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp201 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp202 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp203 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp204 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp205 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp206 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp207 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp208 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp209 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp210 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp211 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp212 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp213 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp214 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp215 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp216 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp217 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp218 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp219 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp220 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp221 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp222 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp223 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp224 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp225 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp226 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp227 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp228 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp229 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp230 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp231 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp232 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp233 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp234 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp235 = tl.load(in_ptr0 + x0, xmask, eviction_policy='evict_last')
    tmp236 = tl.load(in_ptr