Okay, I need to replace the original PyTorch forward pass of the Model with custom Triton kernels. Let me first understand the original computation. The model does a linear transformation (GEMM), applies a sigmoid, multiplies by a scaling factor, adds the original input, and returns the result. The goal is to optimize each of these steps with Triton kernels, possibly fusing them where possible.

First, the linear layer is a simple GEMM. The original code uses torch.nn.Linear, which is a standard matrix multiplication plus bias. The bias addition is a separate elementwise addition. In the Triton implementation, I can replace the GEMM with a Triton matrix multiplication kernel that also handles the bias addition in the same kernel. This would reduce the number of memory transfers.

Next, the sigmoid activation. PyTorch's torch.sigmoid is a per-element operation. I can implement a Triton kernel that computes the sigmoid for each element of the resulting matrix. The sigmoid formula is 1/(1 + exp(-x)). The kernel needs to load the values, compute the exponent, add 1, and then take the reciprocal. I need to be careful with numerical stability, but for now, the Triton kernel can be a straightforward elementwise sigmoid.

After the sigmoid, the scaling factor is applied. This is another elementwise multiplication. The scaling factor is a scalar, so the kernel can load the scaled tensor, multiply each element by the scalar, and store the result. This is a simple kernel that can be written with a single load and store per element.

Then, the original input is added back. The original input is the same as the input to the linear layer, which after the GEMM is stored in a temporary buffer. The addition is a per-element addition of the scaled sigmoid output and the original input. This can be another elementwise Triton kernel, or it can be fused with the scaling kernel if the scaling factor is applied before the addition.

Now, considering the hardware, the A100 has tensor cores that are most efficient for FP16, BF16, or TF32. The original GEMM uses FP32 (the default for nn.Linear). However, the sigmoid and scaling might be better in FP16 or BF16. The Triton kernels can be written to use FP16, which would allow the tensor cores to process the matrix multiplication faster. The scaling factor is a scalar, so it can be a FP16 constant.

For the GEMM kernel, the Triton implementation needs to handle the matrix multiplication with bias. The standard GEMM pattern is a block of rows processed by each program. The kernel loads a block of the input matrix (batch x input_size) and the weight matrix (input_size x hidden_size). The bias is added after the matrix multiplication. The kernel uses shared memory to store intermediate results, but since the bias is a per-row addition, it can be broadcasted efficiently.

The sigmoid kernel then processes the output of the GEMM (shape (batch, hidden_size)). Each program loads a block of elements, computes the sigmoid, and stores the result. Because the sigmoid is a per-element operation, the kernel can be written with a simple block size that matches the row count.

The scaling kernel multiplies each element of the sigmoid output by the scaling factor. Again, a per-element kernel that loads the sigmoid output, multiplies by the scalar, and stores the scaled result.

The addition of the original input and the scaled sigmoid output is a per-element addition. This can be done in a separate kernel or fused with the scaling kernel if the scaling factor is applied before the addition. In the current implementation, the scaling kernel is separate, and then a final addition kernel adds the original input.

Now, the grid calculation for each kernel. The GEMM kernel processes rows of the output tensor. The grid size is the number of rows divided by the block size. The block size for GEMM is chosen as 128 because it fits well with the warp size (32) and allows for multiple warps per block. The sigmoid and scaling kernels each process a contiguous block of elements; their block size is 128 as well, matching the row count when the hidden_size is a multiple of 128.

Shared memory usage: The GEMM kernel uses shared memory to store the intermediate matrix product. The shared memory size is calculated based on the block size and the number of columns (hidden_size). For a block of 128 rows and 8192 columns, the shared memory required would be 128 * 8192 * sizeof(float) which is 1048576 * 4 = 4,194,304 bytes, but the actual implementation uses a smaller shared memory buffer because the bias is added per row after the matrix multiplication. The exact shared memory allocation is handled by the kernel's shared memory pointers.

Masking: All kernels use a mask to handle the last partial block. The mask is generated by comparing the program offset with the total number of elements. This prevents out-of-bounds loads and stores.

Data types: The GEMM kernel uses FP32 because the original linear layer is FP32. The sigmoid and scaling kernels can use FP16 for better tensor core utilization. The final addition kernel uses FP32 to maintain the same precision as the original model.

Autotuning: The kernels are decorated with @triton.jit and the grid is determined by a lambda that calculates the number of blocks. The block size (128) is a compile-time constant chosen based on the expected work per thread and the hardware's warp size.

Putting it all together, the forward pass of the new model first calls a Triton GEMM kernel with bias addition, then a sigmoid kernel, a scaling kernel, and finally an addition kernel that combines the scaled sigmoid output with the original input. Each kernel is launched with a grid that covers the entire tensor, ensuring that every element is processed exactly once.

I need to make sure that the tensors are contiguous in memory before the kernels are called, as the kernels assume contiguous access. The original input is kept as a separate buffer, and the GEMM output is stored in a temporary buffer that is then passed to the sigmoid kernel. The scaling factor is a scalar, so it's passed directly to the scaling kernel.

Finally, the addition of the original input and the scaled sigmoid output is performed in a final Triton kernel that reads both tensors and writes the result to the output buffer. The output buffer has the same shape as the original hidden_size tensor, matching the expected output of the original model.
</think>

```python
import torch
import torch.nn as nn
import triton
import triton.language as tl
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
empty_strided_cuda = torch._C._dynamo.guards._empty_strided_cuda
reinterpret_tensor = torch._C._dynamo.guards._reinterpret_tensor
empty_strided_cuda_0 = torch._C._dynamo.guards._empty_strided_cuda
empty_strided_cuda_1 = torch._C._dynamo.guards._empty_strided_cuda


@triton.jit
def triton_poi_fused_add_gemm_0(in_ptr0, in_ptr1, out_ptr0, xnumel, ynumel,
    xoffset, yoffset, rnumel, rscale, XBLOCK: tl.constexpr):
    xnumel = xnumel
    ynumel = ynumel
    RBLOCK: tl.constexpr = 1
    xoffset = tl.program_id(1) * XBLOCK
    xoffset + tl.arange(0, XBLOCK)[:, None]
    yoffset = yoffset
    yoffset + tl.arange(0, YBLOCK)[None, :]
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK * RBLOCK], True, tl.int1)
    yindex = tl.arange(0, YBLOCK)[None, :]
    yindex = yindex + yoffset
    yindex = yindex % ynumel
    tl.full([XBLOCK, YBLOCK