Okay, I need to replace the matrix multiplication, subtraction, multiplication, and ReLU in the original PyTorch model with custom Triton kernels. Let me break down each step.

First, the original model does a linear layer (matmul), then subtracts a scalar, multiplies by another scalar, and applies ReLU. The goal is to fuse these operations into a single Triton kernel where possible, or split them into kernels that still maintain the performance benefits.

Starting with the linear layer. The linear layer is a GEMM (General Matrix Multiply) of shape (batch, in_features) with (in_features, out_features). The output is (batch, out_features). In Triton, there are existing kernels for GEMM, but the original model uses a simple Linear module, which internally does the GEMM. However, the subsequent operations are scalar sub and mul, so maybe I can fuse the GEMM with the scalar operations into a single kernel that does the matmul, then adds the scalar (subtract_value), multiplies by multiply_value, and applies ReLU. That would save a lot of memory traffic because the intermediate tensors (the result of GEMM) are not stored separately.

Wait, the original code first does a linear, then subtracts a scalar, multiplies by a scalar, then ReLU. So the sequence is: x = linear(x) → x = x - subtract → x = x * multiply → x = ReLU(x). If I can fuse all these into a single kernel that does the GEMM, then the scalar subtraction and multiplication, then ReLU, that would be ideal.

But how does the Triton GEMM kernel work? The standard Triton GEMM kernels (like the ones generated by the external library) take the input tensors, the weight tensor, the bias, and the output. They perform the matrix multiplication, add the bias, and then a ReLU (or other activation). However, in the original model, there is no bias, only a scalar subtraction and multiplication. So maybe I can modify the GEMM kernel to perform the GEMM, then add the scalar (but wait, subtraction is the same as adding a negative scalar). Then multiply by the scalar, and finally apply ReLU.

Wait, the original model subtracts subtract_value, then multiplies by multiply_value. So the combined operation is x = GEMM_result - subtract_value * multiply_value. Because subtraction and multiplication are commutative in that order. Let me check: (a * b) - c = a * b - c. But if the order is first subtract then multiply, it's (a - c) * b. So the scalar operations are not commutative. Therefore, I can't combine them into a single scalar addition. Therefore, the sequence is: GEMM → subtract → multiply → ReLU.

So the Triton kernel needs to perform the GEMM, then subtract the scalar, multiply by the scalar, and then ReLU. How can I implement that in a Triton kernel?

Alternatively, the GEMM kernel can be followed by a scalar subtraction and multiplication, which can be done with elementwise kernels, and then the ReLU can be another kernel. However, the elementwise kernels are simple and can be fused with the GEMM kernel.

But the original model's GEMM is a simple Linear layer with no bias. So the GEMM is (input @ weight) + bias, but in this case, bias is zero. So the GEMM kernel would just compute the matrix product.

So the plan is:

1. Perform the GEMM (input @ weight) using a Triton GEMM kernel. The output is a tensor of shape (batch, out_features).

2. Subtract the scalar (subtract_value) from each element of the GEMM result. This can be an elementwise kernel.

3. Multiply the result by the scalar (multiply_value). Another elementwise kernel.

4. Apply the ReLU activation. Another elementwise kernel.

But each of these elementwise operations is a simple addition, subtraction, multiplication, and max(0, x). These can be implemented with Triton kernels that operate on a contiguous block of the tensor.

However, the elementwise kernels are straightforward and can be written with a single program that processes the entire tensor. The GEMM kernel, on the other hand, is more complex and may need to be a separate kernel.

Wait, the existing Triton GEMM kernels (from the external library) are already highly optimized. So perhaps the best approach is to use the existing Triton GEMM kernel for the matrix multiplication, then use three separate elementwise Triton kernels for the subtraction, multiplication, and ReLU.

But the user's example shows that the addition kernel is fused into a single Triton kernel. So maybe the same approach can be applied here. The GEMM is a separate kernel, then the subtraction and multiplication can be combined into a single elementwise kernel, followed by the ReLU.

Alternatively, the GEMM kernel can be modified to include the scalar operations, but that would require reworking the existing kernel, which is not trivial.

Given that the original model's subsequent operations are elementwise and the GEMM is a standard matrix multiply, the most straightforward path is:

- Use the existing Triton GEMM kernel for the matrix multiplication.

- Use a custom Triton elementwise kernel to subtract the scalar and multiply by the scalar in one pass.

- Use a separate Triton elementwise kernel for the ReLU.

But the user's example fused the addition into a single kernel. So maybe the subtraction and multiplication can be fused as well.

Let me think: the elementwise kernel for subtraction and multiplication would load the GEMM result, subtract the scalar, multiply by the scalar, and store the result. That's a single kernel, which is simple and can be written with a single program that processes the entire tensor.

Then the ReLU is another kernel that loads the intermediate tensor, applies max(0, x), and stores the result.

So the three kernels are:

1. GEMM kernel (external, already present in the Triton library).

2. Elementwise kernel for (x - subtract) * multiply.

3. Elementwise kernel for ReLU.

But the original model uses the Linear module, which does the GEMM, bias, etc. Since there's no bias here, the GEMM kernel can be called with the weight and the input, and the bias can be set to zero.

Now, the Triton GEMM kernel that the user provided in the example is a simple addition, but for the GEMM, the external library's kernel is needed. However, the user is to replace the entire sequence (GEMM + scalar ops + ReLU) with custom Triton kernels. Therefore, the GEMM part must be implemented as a Triton GEMM kernel, followed by the elementwise kernels.

Wait, but the original model's forward is:

x = linear(x) → x = x - subtract → x = x * multiply → x = ReLU(x)

So the GEMM is (input @ weight) + bias (bias is zero). Then subtract scalar, multiply scalar, ReLU.

So the Triton GEMM kernel would compute (input @ weight). The bias is zero, so the kernel can be called with bias_ptr = None or a zero tensor.

Then, the elementwise kernels:

- Subtract scalar and multiply scalar.

- ReLU.

But how to implement the subtraction and multiplication in a single kernel? The kernel would load the GEMM result, subtract the scalar, multiply by the scalar, and store the result.

That kernel is simple: it processes each element, performs two arithmetic operations, and stores the result.

The ReLU kernel is also simple: load the element, compute max(0, x), store.

So the three kernels are:

1. GEMM kernel (external, already present in the Triton library, but the user must import it and call it).

2. Subtract and Multiply kernel (custom, written in Triton).

3. ReLU kernel (custom, written in Triton).

Wait, but the user's example fused the addition into a single kernel. So perhaps the same pattern can be applied here. However, the GEMM is a separate operation and cannot be fused with the elementwise kernels in the same way.

So the final model would be:

- Call the Triton GEMM kernel with the input and weight, producing the GEMM result.

- Call the custom Triton kernel to subtract the scalar and multiply by the scalar.

- Call the custom Triton kernel to apply ReLU.

Thus, the three kernels.

But the user's example only had one elementwise kernel for addition. So in the original problem, the GEMM is separate, and the elementwise operations are fused into one kernel.

Now, the code structure.

The original model has a Linear layer. In the new model, the Linear layer is replaced by the Triton GEMM kernel. The weight is the same as the Linear's weight, and the bias is omitted (since the original model uses a scalar subtraction and multiplication, not a bias).

Wait, the original model's linear layer is initialized with in_features and out_features. The weight is a (out_features, in_features) tensor, and the input is (batch, in_features). The GEMM kernel would compute (batch, in_features) @ (out_features, in_features) → (batch, out_features). So the weight is (out_features, in_features), the input is (batch, in_features). The GEMM kernel would need to be called with these shapes.

In the Triton GEMM kernels, the external library (e.g., the one generated by the external lib) would handle the GEMM. The user would need to import the appropriate GEMM kernel, set the bias to zero, and call it.

But the user's code example uses a custom addition kernel. So for the GEMM, the user would need to import the existing Triton GEMM kernel, and call it with the input, weight, and a zero bias.

Once the GEMM is done, the next step is the elementwise subtraction and multiplication. The custom kernel for that would be written with the same pattern as the addition kernel: a program processes a block of data, loads the value, applies the two operations, stores.

Then the ReLU kernel, which is also a simple elementwise kernel.

So the final code would look like:

import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime import triton_helpers
import torch
import torch.nn as nn
import triton
import triton.language as tl
from torch._inductor.runtime.triton_heuristics import grid
from torch._C import _cuda_getCurrentRawStream as get_raw_stream
from torch._inductor.runtime.triton_helpers import math as tl_math
from torch._inductor.runtime.triton_helpers import lib